name: llm-hub
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - fastapi
  - uvicorn
  - passlib
  - pip:
      - langchain
      - langgraph
      - langchain-aws
      - pydantic[email]