"""Tests for pigar_import_detector.

The detector shells out to the `pigar` CLI. Most tests mock `subprocess.run`
and write a synthetic requirements.txt so the suite does not require pigar
to be installed. One integration test is skipped when pigar is missing.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.factories.pigar_import_detector import detect_required_packages


def _fake_run(requirements_content: str | None):
    """Return a subprocess.run replacement that writes a fixed requirements.txt.

    If requirements_content is None, the replacement skips the write so we can
    simulate pigar producing no output.
    """
    def _runner(cmd, *args, **kwargs):
        # Locate the output path: the token after "-f"
        reqs_path = Path(cmd[cmd.index("-f") + 1])
        if requirements_content is not None:
            reqs_path.write_text(requirements_content)

        class Result:
            returncode = 0
            stdout = ""
            stderr = ""

        return Result()

    return _runner


class TestParse:
    def test_third_party_imports_are_returned(self):
        fake_output = "numpy==1.26.0\npandas==2.1.0\nopencv-python==4.9.0.80\n"
        with patch("subprocess.run", side_effect=_fake_run(fake_output)):
            result = detect_required_packages("import numpy\nimport pandas\nimport cv2\n")
        assert result == ["numpy", "opencv-python", "pandas"]

    def test_stdlib_only_script_returns_empty(self):
        with patch("subprocess.run", side_effect=_fake_run("")):
            result = detect_required_packages("import os\nimport json\nprint(os.getcwd())\n")
        assert result == []

    def test_syntax_invalid_script_returns_empty_without_raising(self):
        with patch("subprocess.run", side_effect=_fake_run(None)):
            result = detect_required_packages("def broken(:\n    pass\n")
        assert result == []

    def test_version_specifiers_are_stripped(self):
        fake_output = "\n".join([
            "requests>=2.28.0",
            "flask~=2.0",
            "django<5.0",
            "rich!=12.0",
            "httpx",
            "celery==5.4.0 ; python_version >= '3.10'",
        ])
        with patch("subprocess.run", side_effect=_fake_run(fake_output)):
            result = detect_required_packages("# any script")
        assert result == ["celery", "django", "flask", "httpx", "requests", "rich"]

    def test_comments_and_blank_lines_are_ignored(self):
        fake_output = "\n".join([
            "# generated by pigar",
            "",
            "numpy==1.26.0  # scientific stuff",
            "# another comment",
            "pandas==2.1.0",
            "",
        ])
        with patch("subprocess.run", side_effect=_fake_run(fake_output)):
            result = detect_required_packages("# any script")
        assert result == ["numpy", "pandas"]

    def test_duplicates_are_deduplicated(self):
        fake_output = "numpy==1.26.0\nnumpy==1.25.0\nNumPy==1.24.0\n"
        with patch("subprocess.run", side_effect=_fake_run(fake_output)):
            result = detect_required_packages("import numpy")
        assert result == ["numpy"]


class TestFailureModes:
    def test_missing_pigar_binary_returns_empty(self):
        with patch("subprocess.run", side_effect=FileNotFoundError("pigar")):
            result = detect_required_packages("import numpy")
        assert result == []

    def test_timeout_returns_empty(self):
        def _raise_timeout(*args, **kwargs):
            raise subprocess.TimeoutExpired(cmd=args[0], timeout=15)

        with patch("subprocess.run", side_effect=_raise_timeout):
            result = detect_required_packages("import numpy")
        assert result == []

    def test_pigar_produces_no_file_returns_empty(self):
        with patch("subprocess.run", side_effect=_fake_run(None)):
            result = detect_required_packages("import numpy")
        assert result == []

    def test_unexpected_exception_returns_empty(self):
        with patch("subprocess.run", side_effect=RuntimeError("boom")):
            result = detect_required_packages("import numpy")
        assert result == []


@pytest.mark.skipif(shutil.which("pigar") is None, reason="pigar CLI not installed")
class TestIntegration:
    def test_real_pigar_detects_common_imports(self):
        script = "import numpy\nimport pandas\nimport os\n"
        result = detect_required_packages(script)
        # stdlib 'os' must not appear; numpy and pandas should be detected
        assert "os" not in result
        assert "numpy" in result
        assert "pandas" in result
